import React, { useState } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Evidence, CAPAReport, ChecklistItem, User } from '../types';
import { Download, Loader2 } from 'lucide-react';
import { COMPANY_NAME, APP_NAME } from '../constants';

interface ReportGeneratorProps {
  evidence: Evidence[];
  capa: CAPAReport[];
  checklists: ChecklistItem[];
  users: User[];
  currentUser: User;
}

const ReportGenerator: React.FC<ReportGeneratorProps> = ({ evidence, capa, checklists, users, currentUser }) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = () => {
    setIsGenerating(true);
    try {
      const doc = new jsPDF('landscape');
      
      // Header
      doc.setFontSize(22);
      doc.setTextColor(30, 58, 138); // Blue 900
      doc.text(`${COMPANY_NAME} - ${APP_NAME}`, 14, 22);
      
      doc.setFontSize(14);
      doc.setTextColor(100);
      doc.text(`Official Audit & Compliance Report`, 14, 32);
      
      doc.setFontSize(10);
      doc.text(`Generated by: ${currentUser.name} (${currentUser.role})`, 14, 40);
      doc.text(`Date: ${new Date().toLocaleString()}`, 14, 46);

      // --- Evidence & Compliance Table ---
      doc.setFontSize(16);
      doc.setTextColor(30, 58, 138);
      doc.text('1. Compliance Evidence Ledger', 14, 60);

      const evidenceData = evidence.map(e => {
        const task = checklists.find(t => t.id === e.checklistItemId);
        const taskName = task?.task || 'Unknown Task';
        const frameworkInfo = task?.framework ? `${task.framework} ${task.control_clause ? `(${task.control_clause})` : ''}` : 'N/A';
        const submitter = users.find(u => u.id === e.userId)?.name || e.userId;

        return [
          e.department,
          taskName,
          frameworkInfo,
          submitter,
          e.status,
          e.submissionDate,
          e.comment.substring(0, 50) + (e.comment.length > 50 ? '...' : '')
        ];
      });

      autoTable(doc, {
        startY: 65,
        head: [['Department', 'Objective / Control', 'Framework', 'Submitter', 'Status', 'Date', 'Context']],
        body: evidenceData,
        theme: 'grid',
        headStyles: { fillColor: [37, 99, 235] },
        styles: { fontSize: 8 }
      });

      // --- CAPA Reports Table ---
      const finalY = (doc as any).lastAutoTable.finalY || 65;
      
      doc.setFontSize(16);
      doc.setTextColor(30, 58, 138);
      doc.text('2. Corrective & Preventive Actions (CAPA)', 14, finalY + 15);

      const capaData = capa.map(c => [
        c.department,
        c.userName,
        c.month,
        c.status,
        c.content.substring(0, 80) + (c.content.length > 80 ? '...' : '')
      ]);

      autoTable(doc, {
        startY: finalY + 20,
        head: [['Department', 'Owner', 'Period', 'Status', 'Action Plan Details']],
        body: capaData,
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229] }, // Indigo
        styles: { fontSize: 8 }
      });

      // Footer
      const pageCount = (doc.internal as any).getNumberOfPages();
      for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Strictly Confidential - ${COMPANY_NAME} Internal Network. Page ${i} of ${pageCount}`, doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 10, { align: 'center' });
      }

      doc.save(`Audit_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF report.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={generatePDF}
      disabled={isGenerating}
      className="flex items-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-xl border border-slate-700 hover:bg-slate-800 transition-all font-bold text-xs uppercase tracking-widest disabled:opacity-50"
    >
      {isGenerating ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
      Export PDF Report
    </button>
  );
};

export default ReportGenerator;
